# Alacritty Config File

[window]
startup_mode = "Maximized"
decorations = "None"
opacity = 0.8

[colors.primary]
background = "0x000000"

[font]
normal = { family = "Comic Code", style = "Medium" }
bold = { family = "Comic Code", style = "Bold" }
size = 17
