font_family Comic Mono
font_size 23

disable_ligatures never

enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no
bell_on_tab no

hide_window_decorations yes

cursor_shape block
cursor_blink_interval 0

shell_integration disabled
