#!/bin/bash

check_arguments() {
  if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <input_file>"
    exit 1
  fi
}

get_filenames() {
  input_file="$1"
  output_file="${input_file%.*}.mp4"
  echo "$input_file" "$output_file"
}

convert_file() {
  ffmpeg -i "$1" -codec copy "$2"
  if [ $? -eq 0 ]; then
    echo "Conversion successful: $2"
  else
    echo "Conversion failed."
    exit 1
  fi
}

main() {
  check_arguments "$@"
  read -r input_file output_file <<< $(get_filenames "$1")
  convert_file "$input_file" "$output_file"
}

main "$@"

