#!/bin/bash

# Script that allows me to convert a file to mp4.

# Check if the correct number of arguments is provided
if [ "$#" -ne 1 ]; then
	echo "Usage: $0 <input_file>"
	exit 1
fi

# Get the input file and output file names
input_file="$1"
output_file="${input_file%.*}.mp4"

# Convert the file
ffmpeg -i "$input_file" -codec copy "$output_file"

# Check if the conversion was successful
if [ $? -eq 0 ]; then
	echo "Conversion successful: $output_file"
else
	echo "Conversion failed."
	exit 1
fi
