# Alacritty Configuration File

[window]
startup_mode = "Maximized"
decorations = "None"

[colors.primary]
background = "0x000000"

[font]
normal = { family = "Comic Mono", style = "Normal"}
size = 18.5
