filetype off
filetype indent off
set guicursor=
set mouse=
set nowrap
set noswapfile
set nobackup
set nowritebackup
set undofile
set undodir=~/.vim/undo
set undolevels=2000
set clipboard=unnamedplus

set t_ti=
set t_te=
let loaded_netrwPlugin = 1

set softtabstop=0
set shiftwidth=0
set noexpandtab
set smartindent
set scrolloff=4

syntax off
colorscheme default
highlight Search ctermfg=black ctermbg=darkyellow
highlight MatchParen ctermfg=white ctermbg=black
highlight NonText ctermfg=white
highlight Normal ctermfg=white

vnoremap <silent> <C-y> :w !xsel -ib<CR><Esc>
nnoremap <silent> <C-y> :"+y<CR>:call system('xsel -ib', getreg('"'))<CR>
